// https://github.com/cloud4dev/jenkins-library-review.git
library identifier: 'jenkins-library-review@main',
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/cloud4dev/jenkins-library-review'])

pipeline {
    agent {
            docker {
                image 'mcr.microsoft.com/dotnet/core/sdk:3.1.101'
            }       

    }


    environment {
        // VERSION="0.0.1"
        // VERSION_RC="rc.2"
    }

    stages {

        stage('Audit tools') {
            steps {
                sh '''
                    dotnet --list-sdks
                    dotnet --list-runtimes
                '''
                sh 'printenv'
                sh 'ls -l "$WORKSPACE"'
            }
        }

        stage('Build') {
            steps {
                echo "Building version ${VERSION} with suffix: ${VERSION_SUFFIX}"
                sh 'dotnet build "$WORKSPACE/using-docker-agent/src/Pi.Web/Pi.Web.csproj"'
            }
        }

        stage('Test') {
            steps {
                dir("$WORKSPACE/using-docker-agent//src") {
                   sh '''
                        dotnet test Pi.Math.Tests/Pi.Math.Tests.csproj
                        dotnet test Pi.Runtime.Tests/Pi.Runtime.Tests.csproj
                    '''
                    mstest testResultsFile:"**/*.trx", keepLongStdio: true 
                }
            }
        }

        stage('Smoke Test') {
            steps {
                sh 'dotnet "$WORKSPACE/./using-docker-agent/src/Pi.Web/bin/Debug/netcoreapp3.1/Pi.Web.dll"'
            }
        }

        
        }

    }
}