// https://github.com/cloud4dev/jenkins-library-review.git
library identifier: 'jenkins-library-review@main',
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/cloud4dev/jenkins-library-review'])

pipeline {
    agent any
    stages {
        stage('Audit tools') {
            steps {
                auditTools()
            }
        }
        
    }
}