// https://github.com/cloud4dev/jenkins-library-review.git
library identifier: 'jenkins-library-review@master',
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/cloud4dev/jenkins-library-review'])

pipeline {
    agent any
    stages {
        stage('Audit Tools') {
            steps {
                auditTools()
            }
        }
    }
}