pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/core/sdk:3.1.101'
        }
    }

    // environment {
    // }

    stages {

        stage('Audit tools') {
            steps {
                sh '''
                    dotnet --list-sdks
                    dotnet --list-runtimes
                '''
                sh 'printenv'
                sh 'ls -l "$WORKSPACE"'
            }
        }

        stage('Build') {
            steps {
                sh 'dotnet build "$WORKSPACE/using-docker-agent/src/Pi.Web/Pi.Web.csproj"'
            }
        }

        stage('Test') {
            steps {
                dir("$WORKSPACE/using-docker-agent/src") {
                   sh '''
                        dotnet test Pi.Math.Tests/Pi.Math.Tests.csproj
                        dotnet test Pi.Runtime.Tests/Pi.Runtime.Tests.csproj
                    '''
                }
            }
        }

        stage('Smoke Test') {
            steps {
                sh 'dotnet "$WORKSPACE/using-docker-agent/src/Pi.Web/bin/Debug/netcoreapp3.1/Pi.Web.dll"'
            }
        }
    }
}
